<?php

namespace App\Enums;

enum ActivityType: string {
    case PROJECT_CREATED = 'PROJECT_CREATED';
    case PHASE_UPDATED = 'PHASE_UPDATED';
    case PROGRESS_UPDATED = 'PROGRESS_UPDATED';
    case DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED';
    case MILESTONE_CREATED = 'MILESTONE_CREATED';
    case MILESTONE_COMPLETED = 'MILESTONE_COMPLETED';
    case USER_JOINED = 'USER_JOINED';
    case BUDGET_UPDATED = 'BUDGET_UPDATED';
    case SAFETY_INCIDENT = 'SAFETY_INCIDENT';
    case QUALITY_CHECK = 'QUALITY_CHECK';
}

